#!/bin/bash

if [[ $1 =~ ^[0-9]*$ ]]; then
  if [ -f /etc/pve/lxc/$1.conf ]; then
    CONTAINER=$1
    COMMAND=$2
    shift
    ARGS=$@
    echo -ne "\e[1;32mprocessing container #${CONTAINER}\e[0m\n"
    pct exec $CONTAINER $COMMAND -- $ARGS
  else
    echo "container $1 does not exist"
    exit 1
  fi
fi
