#!/bin/bash

CONTAINERS=( $(pct list | grep running | awk '{print $1}') )

apt_update() {
pct exec $CONTAINER "apt-get update"
pct exec $CONTAINER "apt-get dist-upgrade -y"
pct exec $CONTAINER "apt-get clean"
pct exec $CONTAINER "apt-get autoremove -y"
}

yum_update() {
pct exec $CONTAINER "yum -y update"
}

apk_update() {
pct exec $CONTAINER "apk upgrade"
}

for CONTAINER in ${CONTAINERS[@]}
do
  pct exec $CONTAINER "which apt-get >/dev/null" && apt_update
  pct exec $CONTAINER "which yum >/dev/null" && yum_update
  pct exec $CONTAINER "which apk >/dev/null" && apk_update
done
